# Generated by Django 5.1 on 2025-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
